### ISSUE TITLE
Vibrant Themes not working in Windows 10

### ISSUE THREAD

**Issue by manikantag** [champloohq/tusk#21] opened 2017-09-21 12:18 UTC
## Description

Not able to switch to 'Vibrant Themes' in Windows 10. `Ctrl + Alt + U/J` is not working.

### Error Message (if any)

No error message

## Environment

OS Type:        Windows_NT
OS Platform:    win32
OS Release:     10.0.15063

**Comment by klauscfhq** [comment] 2017-09-21 12:27
Duplicate of #19

**Closed by klauscfhq** 2017-09-21 12:27 UTC
Labels: duplicate
